### ISSUE TITLE
#TK: Adaptación de pág Quiénes somos a plantilla CSS

### ISSUE THREAD

**Issue by MaEmiliaLuduena** [practicaproISPC/grupo-5-g5#110]
Adaptación de la página html 'Quiénes somos' a plantilla CSS que hayamos elegido

**Comment by leiva7** [comment]
- [ ] Crear página sobre el proyecto
- [ ] Adaptar la foto del logo
- [ ] Agregar la foto del logo
- [ ] Adaptar otras fotos a formato web
- [ ] Ordenar las carpetas
- [ ] Modificar los links y redireccionar el footer
- [ ] Mover botón Enviar del loggin Admin

**Comment by leiva7** [comment]
Linkee secciones del sitio sobre nosotros
