### ISSUE TITLE
#TK Verificar Accesibilidad de las Paginas

### ISSUE THREAD

**Issue by GuadaMongeBarale** [practicaproISPC/grupo-5-g5#215]

**Comment by leiva7** [comment]
Explorado con la herramienta Wave, en los contrastes hay varios falsos positivos, por ejemplo en la barra de menú porque el wave no lee el color de fondo:
![image](https://user-images.githubusercontent.com/50720334/141227895-fe3ceecc-dac2-4b08-bc0c-5ff52070736c.png)

Cuando en realidad si exploramos con el color que corresponde da ok en AA.

![image](https://user-images.githubusercontent.com/50720334/141227724-06766a70-c9b8-4004-b7a8-8e5b6ae76863.png)

**Comment by leiva7** [comment]
Se realizaron mejoras pasando de:
![image](https://user-images.githubusercontent.com/50720334/141228548-60856da9-b6f3-4f07-98eb-01007c67e2fb.png)


a: 
![image](https://user-images.githubusercontent.com/50720334/141228667-728ae3fb-9c09-4f92-9dbe-0f73d5d7a8e3.png)
(algunos de los cuales falsos positivos)
