### ISSUE TITLE
#TK: Redactar Descripción general

### ISSUE THREAD

**Issue by GuadaMongeBarale** [practicaproISPC/grupo-5-g5#60]

**Comment by GuadaMongeBarale** [comment]
En el pdf  "Especicacion de Requisitos segun el estandar de IEEE 830" Encontré algunos puntos que no están en el word que nos pasaron los profes.

Este punto no entendí bien como completarlo. 

2.1. Perspectiva del Producto
Esta subseccion debe relacionar el futuro sistema (producto software) con
otros productos. Si el producto es totalemente independiente de otros productos,
tambien debe especicarse aquí. Si la ERS dene un producto que
es parte de un sistema mayor, esta subseccion relacionara los requisitos del
sistema mayor con la funcionalidad del producto descrito en la ERS, y se
identicaran las interfaces entre el producto mayor y el producto aquí descrito.
Se recomienda utilizar diagramas de bloques.

Por otro lado también tengo dudas si estaría bien lo que redacte sobre descripción general  y características de los usuarios.

El punto 2.2 Funciones del Producto lo hago también?

**Comment by leiva7** [comment]
> En el pdf "Especicacion de Requisitos segun el estandar de IEEE 830" Encontré algunos puntos que no están en el word que nos pasaron los profes.
> 
> Este punto no entendí bien como completarlo.
> 
> 2.1. Perspectiva del Producto
> Esta subseccion debe relacionar el futuro sistema (producto software) con
> otros productos. Si el producto es totalemente independiente de otros productos,
> tambien debe especicarse aquí. Si la ERS dene un producto que
> es parte de un sistema mayor, esta subseccion relacionar�a los requisitos del
> sistema mayor con la funcionalidad del producto descrito en la ERS, y se
> identicaran las interfaces entre el producto mayor y el producto aquí descrito.
> Se recomienda utilizar diagramas de bloques.

_Se me ocurre que esto podría ser explicar que si se lo vendemos a alguien que ya tenga un sitio web, y una base de datos de clientes o contactos para la venta, este sistema va a estar interactuando con esos dos sistemas por ej_ 

> Por otro lado también tengo dudas si estaría bien lo que redacte sobre descripción general y características de los usuarios.
> 
> El punto 2.2 Funciones del Producto lo hago también?

_Me parece que en la clase dijeron que nosotros trabajábamos con una versión abreviada, solo con los puntos que nos pusieron en el modelo._
