### ISSUE TITLE
#US Testeo 2 Sprint 

### ISSUE THREAD

**Issue by GuadaMongeBarale** [practicaproISPC/grupo-5-g5#86]
Como programador quiero revisar mi trabajo para que funcione según lo previsto

**Comment by leiva7** [comment]
- [ ] Ver cómo hacer para que del formulario al registro de la base de datos no haya problemas con las ñ

**Comment by leiva7** [comment]
Investigación que funciona sobre problema de las ñ: 
https://www.oscarperez.es/problemas-con-las-enes-acentos-y-demas-caracteres-cuando-usas-mysql-y-php/
Lo probé localmente por el tema de que mi archivo de base de datos está diferente del resto - convertir en issue y definir cómo compartir
